/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package GUI;
import Gestion_votos.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author sherlock
 */
public class Acta_electoral extends javax.swing.JFrame {

    /** Creates new form Acta_electoral */
    private Mesa mesa;
    private Eleccion eleccion;
    
    public void setdatos( Mesa mesa1,Eleccion eleccion){
        this.mesa=mesa1;
        this.eleccion=eleccion;
        mostrarCandidatos();
        candidato();
        actualizar();
        informe();
    }
    public Acta_electoral() {
        initComponents();
        setDefaultCloseOperation(Candidatos.DISPOSE_ON_CLOSE);
    }
    public void informe(){
     if (Observacion_CheckBox.isSelected()) {
        Observacion_TextField.setEnabled(true);
    } else {
       Observacion_TextField.setEnabled(false); 
        Observacion_TextField.setText("");
    }
}
    public void mostrarCandidatos() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) Candidato_ComboBox.getModel();
        model.removeAllElements();
        Lista<Candidato>candidato=eleccion.getCandidatos();
        Nodo <Candidato> candi=candidato.getCabeza();
        model.addElement("----------");
        while(candi!=null){
            
            model.addElement(candi.getElemento().getNombre());
            candi=candi.getSgteNodo();
        }
    }
    public void candidato(){
        
        Candidato_ComboBox.addActionListener(e->{
        String seleccion=(String)Candidato_ComboBox.getSelectedItem();
            if(!"----------".equals(seleccion)){
            actualizar();
        }
    });
    }
    public void actualizar(){  
            Presidente_TextField.setText("");
            Secretario_TextField.setText("");
            Vocal_TextField.setText("");
            Fecha_TextField.setText("");
            Lugar_TextField.setText("");
            Id_mesa_TextField.setText("");
            Blanco_TextField.setText("");
            Nulo_TextField.setText("");
            Efectivo_TextField.setText("");
            Valido_TextField.setText("");
            if(mesa.encontrarTipo("Presidente")){
                Presidente_TextField.setText(mesa.mostrarMiembro("Presidente"));
            }
            if(mesa.encontrarTipo("Secretario")){
                Secretario_TextField.setText(mesa.mostrarMiembro("Secretario"));
            }
            if(mesa.encontrarTipo("Vocal")){
                Vocal_TextField.setText(mesa.mostrarMiembro("Vocal"));
            }
            Lugar_TextField.setText(mesa.getUbicacion());
            Fecha_TextField.setText(eleccion.getFecha());
            Valido_TextField.setText( Integer.toString(mesa.getActa().voto_efectivo()));
            Blanco_TextField.setText( Integer.toString(mesa.getActa().Voto_blanco_nulo("Voto blanco")));
            Nulo_TextField.setText( Integer.toString(mesa.getActa().Voto_blanco_nulo("Voto nulo")));
            Candidato ganador=mesa.getActa().ganador();
               if (ganador != null) {
        System.out.println("Ganador encontrado: " + ganador.getNombre());
        Ganador_TextField.setText(ganador.getNombre());
        Resultado_TextField.setText(Integer.toString(eleccion.Voto_candidato_total(ganador.getDni())));
               }
            String valor2= (String) Candidato_ComboBox.getSelectedItem();
        if(!valor2.equals("----------")){
            int selec = Candidato_ComboBox.getSelectedIndex()-1;
            Gestion_votos.Candidato candidato=eleccion.candidato_pos(selec);
            System.out.println(candidato.getDni());
            System.out.println("buscando candidato");
            Efectivo_TextField.setText( Integer.toString(mesa.getActa().Voto_candidato(candidato.getDni())));
        }
        Id_mesa_TextField.setText(Integer.toString(mesa.getId()));
       
    }     
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Candidato_ComboBox = new javax.swing.JComboBox<>();
        Blanco_TextField = new javax.swing.JTextField();
        Nulo_TextField = new javax.swing.JTextField();
        Efectivo_TextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Lugar_TextField = new javax.swing.JTextField();
        Fecha_TextField = new javax.swing.JTextField();
        Id_mesa_TextField = new javax.swing.JTextField();
        Secretario_TextField = new javax.swing.JTextField();
        Vocal_TextField = new javax.swing.JTextField();
        Presidente_TextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Valido_TextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Ganador_TextField = new javax.swing.JTextField();
        Resultado_TextField = new javax.swing.JTextField();
        Grabar_Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Observacion_TextField = new javax.swing.JTextArea();
        Observacion_CheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jLabel1.setText("Acta Electoral");

        jLabel2.setText("Voto blanco");

        jLabel3.setText("Voto nulo");

        jLabel4.setText("Voto por candidato");

        Candidato_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Candidato_ComboBoxActionPerformed(evt);
            }
        });

        Blanco_TextField.setEditable(false);
        Blanco_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Blanco_TextFieldActionPerformed(evt);
            }
        });

        Nulo_TextField.setEditable(false);
        Nulo_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nulo_TextFieldActionPerformed(evt);
            }
        });

        Efectivo_TextField.setEditable(false);
        Efectivo_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Efectivo_TextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Fecha");

        jLabel6.setText("Lugar de votacion");

        jLabel7.setText("id mesa electoral");

        jLabel8.setText("Presidente");

        jLabel9.setText("Secretario");

        jLabel10.setText("Vocal");

        Lugar_TextField.setEditable(false);

        Fecha_TextField.setEditable(false);

        Id_mesa_TextField.setEditable(false);
        Id_mesa_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_mesa_TextFieldActionPerformed(evt);
            }
        });

        Secretario_TextField.setEditable(false);

        Vocal_TextField.setEditable(false);

        Presidente_TextField.setEditable(false);

        jLabel11.setText("Votos validos");

        Valido_TextField.setEditable(false);
        Valido_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Valido_TextFieldActionPerformed(evt);
            }
        });

        jLabel12.setText("Ganador de la mesa");

        Ganador_TextField.setEditable(false);
        Ganador_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ganador_TextFieldActionPerformed(evt);
            }
        });

        Resultado_TextField.setEditable(false);

        Grabar_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/disco-flexible.png"))); // NOI18N
        Grabar_Button.setText("Guardar");
        Grabar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Grabar_ButtonActionPerformed(evt);
            }
        });

        Observacion_TextField.setColumns(20);
        Observacion_TextField.setRows(5);
        jScrollPane1.setViewportView(Observacion_TextField);

        Observacion_CheckBox.setText("Incluir observacion");
        Observacion_CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Observacion_CheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Secretario_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Lugar_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Presidente_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Vocal_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(22, 22, 22))
                                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Id_mesa_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Fecha_TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(157, 157, 157)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Valido_TextField)
                            .addComponent(Blanco_TextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Nulo_TextField)
                            .addComponent(Candidato_ComboBox, 0, 211, Short.MAX_VALUE)
                            .addComponent(Ganador_TextField)
                            .addComponent(Efectivo_TextField)
                            .addComponent(Resultado_TextField))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(294, 294, 294))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Observacion_CheckBox))
                                .addGap(289, 289, 289))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Grabar_Button)
                                .addGap(353, 353, 353))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lugar_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Id_mesa_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Presidente_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(Secretario_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Vocal_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(Ganador_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Fecha_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(Valido_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Blanco_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Nulo_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Candidato_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addComponent(Efectivo_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Resultado_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Observacion_CheckBox)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(Grabar_Button)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Candidato_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Candidato_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Candidato_ComboBoxActionPerformed

    private void Nulo_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nulo_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nulo_TextFieldActionPerformed

    private void Blanco_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Blanco_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Blanco_TextFieldActionPerformed

    private void Efectivo_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Efectivo_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Efectivo_TextFieldActionPerformed

    private void Valido_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Valido_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Valido_TextFieldActionPerformed

    private void Id_mesa_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_mesa_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_mesa_TextFieldActionPerformed

    private void Grabar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Grabar_ButtonActionPerformed
        // TODO add your handling code here:
        String info=Observacion_TextField.getText();
        if(!info.isEmpty()){
            mesa.getActa().setObservaciones(info);
            JOptionPane.showMessageDialog(this, "Observacion guardado", "Guardado", JOptionPane.INFORMATION_MESSAGE);
        }
        eleccion.setEstado(false);
    }//GEN-LAST:event_Grabar_ButtonActionPerformed

    private void Observacion_CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Observacion_CheckBoxActionPerformed
        // TODO add your handling code here:
        informe();
    }//GEN-LAST:event_Observacion_CheckBoxActionPerformed

    private void Ganador_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ganador_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ganador_TextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acta_electoral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acta_electoral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acta_electoral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acta_electoral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acta_electoral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Blanco_TextField;
    private javax.swing.JComboBox<String> Candidato_ComboBox;
    private javax.swing.JTextField Efectivo_TextField;
    private javax.swing.JTextField Fecha_TextField;
    private javax.swing.JTextField Ganador_TextField;
    private javax.swing.JButton Grabar_Button;
    private javax.swing.JTextField Id_mesa_TextField;
    private javax.swing.JTextField Lugar_TextField;
    private javax.swing.JTextField Nulo_TextField;
    private javax.swing.JCheckBox Observacion_CheckBox;
    private javax.swing.JTextArea Observacion_TextField;
    private javax.swing.JTextField Presidente_TextField;
    private javax.swing.JTextField Resultado_TextField;
    private javax.swing.JTextField Secretario_TextField;
    private javax.swing.JTextField Valido_TextField;
    private javax.swing.JTextField Vocal_TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
