
package GUI;

import Gestion_votos.*;
import java.util.Arrays;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sherlock
 */
public class Candidatos extends javax.swing.JFrame {

    private int row;
    private Eleccion elec;

    public void setdatos(int row){
        this.row=row;
        this.elec=Gestion_votos.Datos.data.eleccion_pos(row);
        mostrarCandidatos();
    }
    public Candidatos() {
        initComponents();

        setDefaultCloseOperation(Candidatos.DISPOSE_ON_CLOSE);
    }
        public void mostrarCandidatos() {
        DefaultTableModel model = (DefaultTableModel) Candidato_Table.getModel();
        model.setRowCount(0);
        String[][] candidatos = elec.mostrarCandidato_row();

        for (String[] candidato : candidatos) {    
            System.out.println(Arrays.toString(candidato));
            model.addRow(new Object[]{candidato[0], candidato[1],candidato[2],candidato[3] ,false});
    }
       
        
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Candidatos_jLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Candidato_Table = new javax.swing.JTable();
        Agregar_Button = new javax.swing.JButton();
        Eliminar_Button = new javax.swing.JButton();
        Editar_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Candidatos_jLabel.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        Candidatos_jLabel.setText("Candidatos");

        Candidato_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Nombre","Apellido" ,"Partido", "seleccionar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false,false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Candidato_Table);
        if (Candidato_Table.getColumnModel().getColumnCount() > 0) {
            Candidato_Table.getColumnModel().getColumn(0).setResizable(false);
            Candidato_Table.getColumnModel().getColumn(1).setResizable(false);
            Candidato_Table.getColumnModel().getColumn(2).setResizable(false);
        }

        Agregar_Button.setText("Agregar");
        Agregar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_ButtonActionPerformed(evt);
            }
        });

        Eliminar_Button.setText("Eliminar");
        Eliminar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_ButtonActionPerformed(evt);
            }
        });

        Editar_Button.setText("Editar");
        Editar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addComponent(Candidatos_jLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Agregar_Button)
                                .addGap(83, 83, 83)
                                .addComponent(Eliminar_Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Editar_Button)))))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Candidatos_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agregar_Button)
                    .addComponent(Eliminar_Button)
                    .addComponent(Editar_Button))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Agregar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_ButtonActionPerformed
        // TODO add your handling code here:
        Agregar_candidatos formulario = new Agregar_candidatos();
        formulario.setDatos(elec);
        formulario.setVisible(true);
        formulario.addWindowListener(new java.awt.event.WindowAdapter() {
        public void windowClosed(java.awt.event.WindowEvent windowEvent) {
          mostrarCandidatos();
        }
    });
    }//GEN-LAST:event_Agregar_ButtonActionPerformed
    private void eliminarFilasSeleccionadas() {
            DefaultTableModel model = (DefaultTableModel)Candidato_Table.getModel();
        // Recorremos las filas en la tabla (de atrás hacia adelante para evitar problemas de índices al eliminar)
        for (int i = model.getRowCount()-1; i >= 0; i--) {
            Boolean isSelected = (Boolean) model.getValueAt(i, 4); // Comprobar si está marcado el checkbox
            if (isSelected != null && isSelected) {
                System.out.println(i);
                elec.eliminar_candidato(i+1);
                mostrarCandidatos();
              
               
            }
            
        }
        mostrarCandidatos();
    }
    private void Eliminar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_ButtonActionPerformed
        // TODO add your handling code here:
        eliminarFilasSeleccionadas();
        mostrarCandidatos();
    }//GEN-LAST:event_Eliminar_ButtonActionPerformed

    private void Editar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar_ButtonActionPerformed
        // TODO add your handling code here:
        Editar_candidatos formulario = new Editar_candidatos();
        int selec = Candidato_Table.getSelectedRow();
        if (selec != -1) {
            Boolean bol = (Boolean) Candidato_Table.getValueAt(selec, 4);
            if (bol != null && bol) {
            String DNI = (String) Candidato_Table.getValueAt(selec, 0);
            String Nombre = (String) Candidato_Table.getValueAt(selec, 1);
            String Apellido = (String) Candidato_Table.getValueAt(selec, 2);
            String Partido = (String) Candidato_Table.getValueAt(selec, 3);
            formulario.setDatos(elec,selec);
            formulario.setVisible(true);
            formulario.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
            mostrarCandidatos();
        }});           
            }} 
    }//GEN-LAST:event_Editar_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Candidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Candidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Candidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Candidatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Candidatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_Button;
    private javax.swing.JTable Candidato_Table;
    private javax.swing.JLabel Candidatos_jLabel;
    private javax.swing.JButton Editar_Button;
    private javax.swing.JButton Eliminar_Button;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
