
package GUI;
import Gestion_votos.*;
import java.text.ParseException;
import java.util.Date;
import javax.swing.JTextField;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
public class Editar_elecciones extends javax.swing.JFrame {
    /** Creates new form Agregar */
    private String fecha;
    private String Tipo;
    private int id;
    public Editar_elecciones() {
        initComponents();
        setDefaultCloseOperation(Editar_elecciones.DISPOSE_ON_CLOSE);
    }
     public void setDatos(int id, String fecha, String tipo) {
        this.id= id;
        this.fecha=fecha;
        this.Tipo=tipo;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        guardar_Button = new javax.swing.JButton();
        cancelar_Button = new javax.swing.JButton();
        tipo_elec_ComboBox = new javax.swing.JComboBox<>();
        Fecha_jcalender = new com.toedter.calendar.JDateChooser();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Fecha");

        jLabel2.setText("Tipo de eleccion");

        guardar_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/disco-flexible.png"))); // NOI18N
        guardar_Button.setText("Guardar");
        guardar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_ButtonActionPerformed(evt);
            }
        });

        cancelar_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/boton-eliminar.png"))); // NOI18N
        cancelar_Button.setText("Cancelar");
        cancelar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar_ButtonActionPerformed(evt);
            }
        });

        tipo_elec_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------", "Municipal", "Nacional", "Referendum" }));
        tipo_elec_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_elec_ComboBoxActionPerformed(evt);
            }
        });

        Fecha_jcalender.getDateEditor().setEnabled(true);
        ((JTextField)Fecha_jcalender.getDateEditor().getUiComponent()).setEditable(false);
        ((JTextField)Fecha_jcalender.getDateEditor().getUiComponent()).setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guardar_Button)
                .addGap(100, 100, 100)
                .addComponent(cancelar_Button)
                .addGap(126, 126, 126))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tipo_elec_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Fecha_jcalender, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(Fecha_jcalender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tipo_elec_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar_Button)
                    .addComponent(cancelar_Button))
                .addGap(46, 46, 46))
        );

        tipo_elec_ComboBox.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_ButtonActionPerformed
        // TODO add your handling code here:
    Date ofecha = Fecha_jcalender.getDate();
    String fechaStr = "";
    SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
    Date fecha2 = null;
        try {
            fecha2 = formato.parse(fecha);
        } catch (ParseException ex) {
            Logger.getLogger(Editar_elecciones.class.getName()).log(Level.SEVERE, null, ex);
        }

    if (ofecha != null && !ofecha.before(fecha2)) {
        SimpleDateFormat text = new SimpleDateFormat("dd-MM-yyyy");
        fechaStr = text.format(ofecha);
    }else{
        JOptionPane.showMessageDialog(this, "Por favor, seleccione una fecha valida", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    String valorcombo_box = (String) tipo_elec_ComboBox.getSelectedItem();
    
    if (valorcombo_box.equals("----------")) {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione el tipo de elección", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    Gestion_votos.Datos.data.modificarEleccion(id, fechaStr, valorcombo_box);
    this.dispose();
    
    }//GEN-LAST:event_guardar_ButtonActionPerformed

    private void tipo_elec_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_elec_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_elec_ComboBoxActionPerformed

    private void cancelar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar_ButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelar_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editar_elecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editar_elecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editar_elecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editar_elecciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
   

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editar_elecciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Fecha_jcalender;
    private javax.swing.JButton cancelar_Button;
    private javax.swing.JButton guardar_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> tipo_elec_ComboBox;
    // End of variables declaration//GEN-END:variables

}
