/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package GUI;
import Gestion_votos.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author sherlock
 */
public class Informe extends javax.swing.JFrame {

    /** Creates new form Acta_electoral */
    private int row;
    private Eleccion eleccion;
    
    public void setdatos(int row){
        this.row=row;
        this.eleccion=Gestion_votos.Datos.data.eleccion_pos(row);
        mostrarCandidatos();
        candidato();
        actualizar();
        
    }

    public Informe() {
        initComponents();
        setDefaultCloseOperation(Informe.DISPOSE_ON_CLOSE);
    }

    public void mostrarCandidatos() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) Candidato_ComboBox.getModel();
        model.removeAllElements();
        Lista<Candidato>candidato=eleccion.getCandidatos();
        Nodo <Candidato> candi=candidato.getCabeza();
        model.addElement("----------");
        while(candi!=null){
            
            model.addElement(candi.getElemento().getNombre());
            candi=candi.getSgteNodo();
        }
    }
    public void candidato(){
        
        Candidato_ComboBox.addActionListener(e->{
        String seleccion=(String)Candidato_ComboBox.getSelectedItem();
            if(!"----------".equals(seleccion)){
            actualizar();
        }
    });
    }
public void actualizar() {
    System.out.println("Iniciando actualización...");
    
    Blanco_TextField.setText("");
    Nulo_TextField.setText("");
    Efectivo_TextField.setText("");
    Valido_TextField.setText("");
    
    Total_TextField.setText(Integer.toString(eleccion.votos_totales()));
    System.out.println("Calculando votos 1...");
    Valido_TextField.setText(Integer.toString(eleccion.voto_efectivo_total()));
    System.out.println("Calculando votos 2...");
    Blanco_TextField.setText(Integer.toString(eleccion.votos_totales_blancos()));
    Nulo_TextField.setText(Integer.toString(eleccion.votos_totales_nulos()));
    
    System.out.println("Obteniendo ganador...");
    Candidato ganador = eleccion.ganador_eleccion();
    System.out.println("Obteniendo ganador listo .");
    if (ganador != null) {
        System.out.println("Ganador encontrado: " + ganador.getNombre());
        Ganador_TextField.setText(ganador.getNombre());
        Resultado_TextField.setText(Integer.toString(eleccion.Voto_candidato_total(ganador.getDni())));
    }
    
    System.out.println("Actualizando votos de candidato...");
    String valor2 = (String) Candidato_ComboBox.getSelectedItem();
    if (!"----------".equals(valor2)) {
        int selec = Candidato_ComboBox.getSelectedIndex() - 1;
        Candidato candidato = eleccion.candidato_pos(selec);
        if (candidato != null) {
            Efectivo_TextField.setText(Integer.toString(eleccion.Voto_candidato_total(candidato.getDni())));
        }
    }

    System.out.println("Actualización completada.");
}    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Candidato_ComboBox = new javax.swing.JComboBox<>();
        Blanco_TextField = new javax.swing.JTextField();
        Nulo_TextField = new javax.swing.JTextField();
        Efectivo_TextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Valido_TextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Ganador_TextField = new javax.swing.JTextField();
        Resultado_TextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Total_TextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("sansserif", 3, 24)); // NOI18N
        jLabel1.setText("INFORME");

        jLabel2.setText("Voto blanco totales");

        jLabel3.setText("Voto nulo totales");

        jLabel4.setText("Voto por candidato");

        Candidato_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Candidato_ComboBoxActionPerformed(evt);
            }
        });

        Blanco_TextField.setEditable(false);
        Blanco_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Blanco_TextFieldActionPerformed(evt);
            }
        });

        Nulo_TextField.setEditable(false);
        Nulo_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nulo_TextFieldActionPerformed(evt);
            }
        });

        Efectivo_TextField.setEditable(false);
        Efectivo_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Efectivo_TextFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Votos validos totales");

        Valido_TextField.setEditable(false);
        Valido_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Valido_TextFieldActionPerformed(evt);
            }
        });

        jLabel12.setText("Ganador de la eleccion");

        Ganador_TextField.setEditable(false);

        Resultado_TextField.setEditable(false);

        jLabel13.setText("numero total de votantes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(jLabel1)
                .addContainerGap(358, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Blanco_TextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Nulo_TextField)
                            .addComponent(Candidato_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ganador_TextField)
                            .addComponent(Efectivo_TextField)
                            .addComponent(Resultado_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Total_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(Valido_TextField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Total_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(Valido_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Blanco_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Nulo_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Candidato_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(Efectivo_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Ganador_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Resultado_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Candidato_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Candidato_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Candidato_ComboBoxActionPerformed

    private void Nulo_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nulo_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Nulo_TextFieldActionPerformed

    private void Blanco_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Blanco_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Blanco_TextFieldActionPerformed

    private void Efectivo_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Efectivo_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Efectivo_TextFieldActionPerformed

    private void Valido_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Valido_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Valido_TextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Blanco_TextField;
    private javax.swing.JComboBox<String> Candidato_ComboBox;
    private javax.swing.JTextField Efectivo_TextField;
    private javax.swing.JTextField Ganador_TextField;
    private javax.swing.JTextField Nulo_TextField;
    private javax.swing.JTextField Resultado_TextField;
    private javax.swing.JTextField Total_TextField;
    private javax.swing.JTextField Valido_TextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

}
