/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Gestion_votos.*;
import java.util.Arrays;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author O15134
 */
public class Registrar_voto extends javax.swing.JFrame {

    /**
     * Creates new form Registrar_voto
     */
   private Mesa mesa;
   private Eleccion eleccion;
   private Gestion_votos.Acta_electoral acta;
    public void setdatos( Mesa mesa1,Eleccion eleccion){
        this.mesa=mesa1;
        this.eleccion=eleccion;
        acta=mesa.getActa();
        activar_candidato();
        
        
    }
    public Registrar_voto() {
        initComponents();

        setDefaultCloseOperation(Registrar_voto.DISPOSE_ON_CLOSE);
    }
    public void mostrarCandidatos() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) Candidato_ComboBox.getModel();
        model.removeAllElements();
        Lista<Candidato>candidato=eleccion.getCandidatos();
        Nodo <Candidato> candi=candidato.getCabeza();
        model.addElement("----------");
        while(candi!=null){
            
            model.addElement(candi.getElemento().getNombre());
            candi=candi.getSgteNodo();
        }
    }
    public void activar_candidato(){
        Candidato_ComboBox.setEnabled(false);
        Tipo_voto_ComboBox.addActionListener(e->{
        String seleccion=(String)Tipo_voto_ComboBox.getSelectedItem();
            if("Voto efectivo".equals(seleccion)){
            Candidato_ComboBox.setEnabled(true);
            mostrarCandidatos();
        }else{
            Candidato_ComboBox.setEnabled(false);
        }
    });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Tipo_voto_ComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Candidato_ComboBox = new javax.swing.JComboBox<>();
        Guardar_Button = new javax.swing.JButton();
        Cancelar_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("REGISTRAR VOTO");

        Tipo_voto_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------", "Voto nulo", "Voto blanco", "Voto efectivo" }));
        Tipo_voto_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tipo_voto_ComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Voto");

        jLabel3.setText("Candidato");

        Candidato_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Candidato_ComboBoxActionPerformed(evt);
            }
        });

        Guardar_Button.setText("Guardar");
        Guardar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Guardar_ButtonActionPerformed(evt);
            }
        });

        Cancelar_Button.setText("Cancelar");
        Cancelar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Guardar_Button)
                .addGap(50, 50, 50)
                .addComponent(Cancelar_Button)
                .addGap(245, 245, 245))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Tipo_voto_ComboBox, 0, 205, Short.MAX_VALUE)
                            .addComponent(Candidato_ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Tipo_voto_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Candidato_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancelar_Button)
                    .addComponent(Guardar_Button))
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Guardar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Guardar_ButtonActionPerformed
        // TODO add your handling code here:
        String valor= (String) Tipo_voto_ComboBox.getSelectedItem();
        if (valor.equals("----------")) {
        // Si el JComboBox está vacío o no tiene un valor seleccionado
            JOptionPane.showMessageDialog(this, "Por favor, seleccione algun voto", "Error", JOptionPane.ERROR_MESSAGE);
            return;
    }
        Gestion_votos.Voto voto=new Gestion_votos.Voto(valor);


    if(valor.equals("Voto efectivo")){
        String valor2= (String) Candidato_ComboBox.getSelectedItem();
        if(valor2.equals("----------")){
            JOptionPane.showMessageDialog(this, "Por favor, seleccione algun candidato", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
                
        int selec = Candidato_ComboBox.getSelectedIndex()-1;
        Gestion_votos.Candidato candidato=eleccion.candidato_pos(selec);
        voto.setCandidato(candidato);
        
        System.out.println("Voto guardado: " + voto.getTipo() + " - Candidato: " + voto.getCandidato());
    }
        
        acta.agregarVoto(voto);
        
        System.out.println("Voto guardado: " + voto.getTipo());
    }//GEN-LAST:event_Guardar_ButtonActionPerformed

    private void Candidato_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Candidato_ComboBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Candidato_ComboBoxActionPerformed

    private void Tipo_voto_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tipo_voto_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tipo_voto_ComboBoxActionPerformed

    private void Cancelar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar_ButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Cancelar_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar_voto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar_voto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar_voto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar_voto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar_voto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar_Button;
    private javax.swing.JComboBox<String> Candidato_ComboBox;
    private javax.swing.JButton Guardar_Button;
    private javax.swing.JComboBox<String> Tipo_voto_ComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
